export const COMPLAINT_LIST_REQUEST = "COMPLAINT_LIST_REQUEST";
export const COMPLAINT_LIST_SUCCESS = "COMPLAINT_LIST_SUCCESS";
export const COMPLAINT_LIST_FAIL = "COMPLAINT_LIST_FAIL";

export const COMPLAINT_CREATE_REQUEST = "COMPLAINT_CREATE_REQUEST";
export const COMPLAINT_CREATE_SUCCESS = "COMPLAINT_CREATE_SUCCESS";
export const COMPLAINT_CREATE_FAIL = "COMPLAINT_CREATE_FAIL";
export const COMPLAINT_CREATE_RESET = "COMPLAINT_CREATE_RESET";

export const COMPLAINT_UPDATE_REQUEST = "COMPLAINT_UPDATE_REQUEST";
export const COMPLAINT_UPDATE_SUCCESS = "COMPLAINT_UPDATE_SUCCESS";
export const COMPLAINT_UPDATE_FAIL = "COMPLAINT_UPDATE_FAIL";
export const COMPLAINT_UPDATE_RESET = "COMPLAINT_UPDATE_RESET";
