export const DASHBOARD_STATS_REQUEST = "DASHBOARD_STATS_REQUEST";
export const DASHBOARD_STATS_SUCCESS = "DASHBOARD_STATS_SUCCESS";
export const DASHBOARD_STATS_FAIL = "DASHBOARD_STATS_FAIL";

export const DASHBOARD_ACTIVITIES_REQUEST = "DASHBOARD_ACTIVITIES_REQUEST";
export const DASHBOARD_ACTIVITIES_SUCCESS = "DASHBOARD_ACTIVITIES_SUCCESS";
export const DASHBOARD_ACTIVITIES_FAIL = "DASHBOARD_ACTIVITIES_FAIL";
