export const FEE_LIST_REQUEST = "FEE_LIST_REQUEST";
export const FEE_LIST_SUCCESS = "FEE_LIST_SUCCESS";
export const FEE_LIST_FAIL = "FEE_LIST_FAIL";

export const FEE_PENDING_REQUEST = "FEE_PENDING_REQUEST";
export const FEE_PENDING_SUCCESS = "FEE_PENDING_SUCCESS";
export const FEE_PENDING_FAIL = "FEE_PENDING_FAIL";

export const FEE_CREATE_REQUEST = "FEE_CREATE_REQUEST";
export const FEE_CREATE_SUCCESS = "FEE_CREATE_SUCCESS";
export const FEE_CREATE_FAIL = "FEE_CREATE_FAIL";
export const FEE_CREATE_RESET = "FEE_CREATE_RESET";

export const FEE_UPDATE_REQUEST = "FEE_UPDATE_REQUEST";
export const FEE_UPDATE_SUCCESS = "FEE_UPDATE_SUCCESS";
export const FEE_UPDATE_FAIL = "FEE_UPDATE_FAIL";
export const FEE_UPDATE_RESET = "FEE_UPDATE_RESET";

export const FEE_STATS_REQUEST = "FEE_STATS_REQUEST";
export const FEE_STATS_SUCCESS = "FEE_STATS_SUCCESS";
export const FEE_STATS_FAIL = "FEE_STATS_FAIL";
